### ISSUE TITLE
Support Slick 3.0

### ISSUE THREAD

**Issue by GoldenZero** [cvogt/slick-action#1]
Hi,

Is there any plans to support Slick 3.0?

Thank you,

**Comment by cvogt** [comment]
Slick 3 has support for this built in

**Comment by cvogt** [comment]
look for DBIO

**Comment by cvogt** [comment]
excluding automatic master/slave scheduling

**Comment by GoldenZero** [comment]
Hi Jan,
Thank you for the prompt reply, I was looking specifically for this feature:
- for a transaction, automatic use slave if only reads are involved, otherwise use master.
  do you know if this's supported in Slick 3.0 (sorry maybe this question goes to Slick repo)

Thanks in advance,

**Comment by cvogt** [comment]
this project only served as a prototype for slick 3.0's since integrated DBIO monad, but master/slave support never made it into slick main line. please open a feature request ticket in slick's github repo and link back to this project. I am not aware of any immediate plans to support this.
